//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMView.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GMView.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap arrow_large {
            get {
                object obj = ResourceManager.GetObject("arrow_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_point {
            get {
                object obj = ResourceManager.GetObject("arrow_point", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_small {
            get {
                object obj = ResourceManager.GetObject("arrow_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrows {
            get {
                object obj = ResourceManager.GetObject("arrows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap back_but {
            get {
                object obj = ResourceManager.GetObject("back_but", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ball {
            get {
                object obj = ResourceManager.GetObject("ball", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap browser {
            get {
                object obj = ResourceManager.GetObject("browser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon config {
            get {
                object obj = ResourceManager.GetObject("config", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap configure {
            get {
                object obj = ResourceManager.GetObject("configure", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap contexthelp {
            get {
                object obj = ResourceManager.GetObject("contexthelp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap crosshair1 {
            get {
                object obj = ResourceManager.GetObject("crosshair1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dashGPSBg {
            get {
                object obj = ResourceManager.GetObject("dashGPSBg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dashGPSOverlay {
            get {
                object obj = ResourceManager.GetObject("dashGPSOverlay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dashGPSWrapped {
            get {
                object obj = ResourceManager.GetObject("dashGPSWrapped", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dashMiniTilesBg {
            get {
                object obj = ResourceManager.GetObject("dashMiniTilesBg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dashMiniTilesWrapped {
            get {
                object obj = ResourceManager.GetObject("dashMiniTilesWrapped", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dashTextBg {
            get {
                object obj = ResourceManager.GetObject("dashTextBg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dashTextBg130 {
            get {
                object obj = ResourceManager.GetObject("dashTextBg130", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dashTrackBg {
            get {
                object obj = ResourceManager.GetObject("dashTrackBg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dashTrackWrapped {
            get {
                object obj = ResourceManager.GetObject("dashTrackWrapped", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dot_small {
            get {
                object obj = ResourceManager.GetObject("dot_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dot1 {
            get {
                object obj = ResourceManager.GetObject("dot1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap exit {
            get {
                object obj = ResourceManager.GetObject("exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap finishmark {
            get {
                object obj = ResourceManager.GetObject("finishmark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap forw_but {
            get {
                object obj = ResourceManager.GetObject("forw_but", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gmview_icon {
            get {
                object obj = ResourceManager.GetObject("gmview_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon gmview_icon1 {
            get {
                object obj = ResourceManager.GetObject("gmview_icon1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gohome {
            get {
                object obj = ResourceManager.GetObject("gohome", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gps_panel {
            get {
                object obj = ResourceManager.GetObject("gps_panel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gps_point {
            get {
                object obj = ResourceManager.GetObject("gps_point", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gps_point_small {
            get {
                object obj = ResourceManager.GetObject("gps_point_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hdop_0_ideal {
            get {
                object obj = ResourceManager.GetObject("hdop_0_ideal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hdop_1_excellent {
            get {
                object obj = ResourceManager.GetObject("hdop_1_excellent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hdop_2_good {
            get {
                object obj = ResourceManager.GetObject("hdop_2_good", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hdop_3_moderate {
            get {
                object obj = ResourceManager.GetObject("hdop_3_moderate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hdop_4_fair {
            get {
                object obj = ResourceManager.GetObject("hdop_4_fair", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon icon_main {
            get {
                object obj = ResourceManager.GetObject("icon_main", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap intro {
            get {
                object obj = ResourceManager.GetObject("intro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lamp_off {
            get {
                object obj = ResourceManager.GetObject("lamp_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lamp_off2 {
            get {
                object obj = ResourceManager.GetObject("lamp_off2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lamp_on {
            get {
                object obj = ResourceManager.GetObject("lamp_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lamp_on2 {
            get {
                object obj = ResourceManager.GetObject("lamp_on2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap largepin {
            get {
                object obj = ResourceManager.GetObject("largepin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap largepin_green {
            get {
                object obj = ResourceManager.GetObject("largepin_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap largepin_red {
            get {
                object obj = ResourceManager.GetObject("largepin_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap largepin_yellow {
            get {
                object obj = ResourceManager.GetObject("largepin_yellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap largepin3 {
            get {
                object obj = ResourceManager.GetObject("largepin3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap largepingreen {
            get {
                object obj = ResourceManager.GetObject("largepingreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap largepinplus {
            get {
                object obj = ResourceManager.GetObject("largepinplus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap largepinplus2 {
            get {
                object obj = ResourceManager.GetObject("largepinplus2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mark_new {
            get {
                object obj = ResourceManager.GetObject("mark_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap markwp_blue {
            get {
                object obj = ResourceManager.GetObject("markwp_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap markwp_green {
            get {
                object obj = ResourceManager.GetObject("markwp_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap markwp_red {
            get {
                object obj = ResourceManager.GetObject("markwp_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap markwp_yellow {
            get {
                object obj = ResourceManager.GetObject("markwp_yellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap move_map {
            get {
                object obj = ResourceManager.GetObject("move_map", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap network {
            get {
                object obj = ResourceManager.GetObject("network", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap personal {
            get {
                object obj = ResourceManager.GetObject("personal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pointBG {
            get {
                object obj = ResourceManager.GetObject("pointBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap record_track {
            get {
                object obj = ResourceManager.GetObject("record_track", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap reload {
            get {
                object obj = ResourceManager.GetObject("reload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rosa {
            get {
                object obj = ResourceManager.GetObject("rosa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap route {
            get {
                object obj = ResourceManager.GetObject("route", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon sat {
            get {
                object obj = ResourceManager.GetObject("sat", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sat_info {
            get {
                object obj = ResourceManager.GetObject("sat_info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap satSmallInUse {
            get {
                object obj = ResourceManager.GetObject("satSmallInUse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap satSmallUnused {
            get {
                object obj = ResourceManager.GetObject("satSmallUnused", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap semitrans128 {
            get {
                object obj = ResourceManager.GetObject("semitrans128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap semitrans128empty {
            get {
                object obj = ResourceManager.GetObject("semitrans128empty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap semitrans64 {
            get {
                object obj = ResourceManager.GetObject("semitrans64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap semitrans64empty {
            get {
                object obj = ResourceManager.GetObject("semitrans64empty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap show_track {
            get {
                object obj = ResourceManager.GetObject("show_track", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap smallpin_green {
            get {
                object obj = ResourceManager.GetObject("smallpin_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap smallpin_red {
            get {
                object obj = ResourceManager.GetObject("smallpin_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap smallpin_yellow {
            get {
                object obj = ResourceManager.GetObject("smallpin_yellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap speedBarMask {
            get {
                object obj = ResourceManager.GetObject("speedBarMask", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap start_pos {
            get {
                object obj = ResourceManager.GetObject("start_pos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap startmark {
            get {
                object obj = ResourceManager.GetObject("startmark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stay {
            get {
                object obj = ResourceManager.GetObject("stay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon test1 {
            get {
                object obj = ResourceManager.GetObject("test1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap track_load {
            get {
                object obj = ResourceManager.GetObject("track_load", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap track_remove {
            get {
                object obj = ResourceManager.GetObject("track_remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap track_save {
            get {
                object obj = ResourceManager.GetObject("track_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap trafOff {
            get {
                object obj = ResourceManager.GetObject("trafOff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap trafOn {
            get {
                object obj = ResourceManager.GetObject("trafOn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap viewmag_ {
            get {
                object obj = ResourceManager.GetObject("viewmag_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap viewmag_1 {
            get {
                object obj = ResourceManager.GetObject("viewmag_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap viewmagfit {
            get {
                object obj = ResourceManager.GetObject("viewmagfit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap white {
            get {
                object obj = ResourceManager.GetObject("white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wizard {
            get {
                object obj = ResourceManager.GetObject("wizard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wp {
            get {
                object obj = ResourceManager.GetObject("wp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap xpaint {
            get {
                object obj = ResourceManager.GetObject("xpaint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoom00 {
            get {
                object obj = ResourceManager.GetObject("zoom00", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoom01 {
            get {
                object obj = ResourceManager.GetObject("zoom01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoom02 {
            get {
                object obj = ResourceManager.GetObject("zoom02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoom03 {
            get {
                object obj = ResourceManager.GetObject("zoom03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoom04 {
            get {
                object obj = ResourceManager.GetObject("zoom04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoom05 {
            get {
                object obj = ResourceManager.GetObject("zoom05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoom06 {
            get {
                object obj = ResourceManager.GetObject("zoom06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoom07 {
            get {
                object obj = ResourceManager.GetObject("zoom07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoom08 {
            get {
                object obj = ResourceManager.GetObject("zoom08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoom09 {
            get {
                object obj = ResourceManager.GetObject("zoom09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoom10 {
            get {
                object obj = ResourceManager.GetObject("zoom10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoom11 {
            get {
                object obj = ResourceManager.GetObject("zoom11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoom12 {
            get {
                object obj = ResourceManager.GetObject("zoom12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoom13 {
            get {
                object obj = ResourceManager.GetObject("zoom13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoom14 {
            get {
                object obj = ResourceManager.GetObject("zoom14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoom15 {
            get {
                object obj = ResourceManager.GetObject("zoom15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoom16 {
            get {
                object obj = ResourceManager.GetObject("zoom16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoom17 {
            get {
                object obj = ResourceManager.GetObject("zoom17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoom18 {
            get {
                object obj = ResourceManager.GetObject("zoom18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
